import type { Metadata } from "next";
import { Lato } from "next/font/google";
// import Head from "next/head"; // Import the Head component
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
// import Providers from "@/components/Providers";

const lato = Lato({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MinutesOwl",
  description: "Generated by MinutesOwl",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      {/* <Providers> */}
      <body
        className={cn(
          "min-h-screen font-sans antialiased grainy",
          lato.className
        )}
      >
        <Navbar />
        {children}
      </body>
      {/* </Providers> */}
    </html>
  );
}
